export const UPDATE_SELECT_OPTIONS_API = 'UPDATE_SELECT_OPTIONS_API'
export const FETCH_SELECT_OPTIONS_API = 'FETCH_SELECT_OPTIONS_API'
export const FETCH_ADD_COMPONENT_API = 'FETCH_ADD_COMPONENT_API'
export const UPDATE_VALUE_SELECTED_API = 'UPDATE_VALUE_SELECTED_API'
