export const DELETE_SECTION = 'DELETE_SECTION'
export const DELETE_COLUMN = 'DELETE_COLUMN'
export const DELETE_COMPONENT = 'DELETE_COMPONENT'

export const DUPLICATE_SECTION = 'DUPLICATE_SECTION'
export const DUPLICATE_COLUMN = 'DUPLICATE_COLUMN'
export const DUPLICATE_COMPONENT = 'DUPLICATE_COMPONENT'

export const UPDATE_SECTION = 'UPDATE_SECTION'
export const UPDATE_COLUMN = 'UPDATE_COLUMN'
export const UPDATE_COMPONENT = 'UPDATE_COMPONENT'
export const UPDATE_CONTAINER = 'UPDATE_CONTAINER'
